[package]
name = "waffles-solana-net-shaper"
description = "Waffle Labs maintained The solana cluster network shaping tool"
version = "1.16.0-alpha.3"
repository = "https://github.com/waffles-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://waffles.so/"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
rand = "0.7.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.83"
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.16.0-alpha.3" }

[[bin]]
name = "solana-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
