[package]
name = "waffles-solana-sdk-macro"
version = "1.15.0.1"
description = "Waffle Labs maintained Solana SDK Macro"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-sdk-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.19"
quote = "1.0"
rustversion = "1.0.7"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
