[package]
name = "waffles-solana-cargo-build-bpf"
version = "1.16.0"
description = "Waffle Labs maintained Compile a local package and all of its dependencies using the Solana SBF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
homepage = "https://waffles.so/"
name = "solana-cargo-build-bpf"
version = "1.16.0"
description = "Compile a local package and all of its dependencies using the Solana SBF SDK"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo", "env"] }
log = { version = "0.4.14", features = ["std"] }
solana-logger = { package = "waffles-solana-logger", path = "../../logger", version = "=1.16.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "..", version = "=1.16.0" }
log = { version = "0.4.17", features = ["std"] }
solana-logger = { path = "../../logger", version = "=1.16.0" }
solana-sdk = { path = "..", version = "=1.16.0" }

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
