[package]
name = "waffles-solana-sbf-rust-dep-crate"
version = "1.16.0-alpha.3"
description = "Waffle Labs maintained Solana SBF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
name = "solana-sbf-rust-dep-crate"
version = "1.16.0-alpha.3"
description = "Solana SBF test program written in Rust"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-sbf-rust-dep-crate"
edition = "2021"

[dependencies]
byteorder = { version = "1", default-features = false }
# list of crates which must be buildable for bpf programs
solana-address-lookup-table-program = { path = "../../../../programs/address-lookup-table", version = "=1.16.0-alpha.3" }
solana-program = { path = "../../../../sdk/program", version = "=1.16.0-alpha.3" }
solana-address-lookup-table-program = { path = "../../../../programs/address-lookup-table", version = "=1.16.0-alpha.3" }
solana-program = { path = "../../../../sdk/program", version = "=1.16.0-alpha.3" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
