[package]
name = "waffles-solana-sbf-rust-simulation"
version = "1.16.0-alpha.1"
description = "Waffle Labs maintained Solana SBF Program Simulation Differences"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
name = "solana-sbf-rust-simulation"
version = "1.16.0-alpha.1"
description = "Solana SBF Program Simulation Differences"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-sbf-rust-simulation"
edition = "2021"

[features]
test-bpf = []

[dependencies]
solana-program = { path = "../../../../sdk/program", version = "=1.16.0-alpha.1" }

[dev-dependencies]
solana-logger = { path = "../../../../logger", version = "=1.16.0-alpha.1" }
solana-program-test = { path = "../../../../program-test", version = "=1.16.0-alpha.1" }
solana-sdk = { path = "../../../../sdk", version = "=1.16.0-alpha.1" }
solana-validator = { path = "../../../../validator", version = "=1.16.0-alpha.1" }
solana-program = { path = "../../../../sdk/program", version = "=1.16.0-alpha.1" }

[dev-dependencies]
solana-logger = { path = "../../../../logger", version = "=1.16.0-alpha.1" }
solana-program-test = { path = "../../../../program-test", version = "=1.16.0-alpha.1" }
solana-sdk = { path = "../../../../sdk", version = "=1.16.0-alpha.1" }
solana-validator = { path = "../../../../validator", version = "=1.16.0-alpha.1" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
