[package]
name = "waffles-solana-bpf-loader-program"
version = "1.15.0"
description = "Waffle Labs maintained Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-bpf-loader-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
libsecp256k1 = "0.6.0"
log = "0.4.17"
rand = "0.7.3"
waffles-solana-measure = { path = "../../measure", version = "=1.15.0" }
waffles-solana-program-runtime = { path = "../../program-runtime", version = "=1.15.0" }
waffles-solana-sdk = { path = "../../sdk", version = "=1.15.0" }
waffles-solana-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.15.0" }
waffles-solana_rbpf = "=0.2.38"
thiserror = "1.0"

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
