cargo publish -p waffles-solana-frozen-abi-macro
cargo publish -p waffles-solana-programs/address-lookup-table
cargo publish -p waffles-solana-account-decoder
cargo publish -p waffles-solana-banks-client
cargo publish -p waffles-solana-banks-interface
cargo publish -p waffles-solana-banks-server
cargo publish -p waffles-solana-bloom
cargo publish -p waffles-solana-bucket_map
cargo publish -p waffles-solana-clap-utils
cargo publish -p waffles-solana-clap-v3-utils
cargo publish -p waffles-solana-cli
cargo publish -p waffles-solana-cli-config
cargo publish -p waffles-solana-cli-output
cargo publish -p waffles-solana-client
cargo publish -p waffles-solana-core
cargo publish -p waffles-solana-download-utils
cargo publish -p waffles-solana-entry
cargo publish -p waffles-solana-faucet
cargo publish -p waffles-solana-frozen-abi
cargo publish -p waffles-solana-frozen-abi/macro
cargo publish -p waffles-solana-genesis
cargo publish -p waffles-solana-genesis-utils
cargo publish -p waffles-solana-geyser-plugin-interface
cargo publish -p waffles-solana-geyser-plugin-manager
cargo publish -p waffles-solana-gossip
cargo publish -p waffles-solana-install
cargo publish -p waffles-solana-keygen
cargo publish -p waffles-solana-ledger
cargo publish -p waffles-solana-ledger-tool
cargo publish -p waffles-solana-local-cluster
cargo publish -p waffles-solana-logger
cargo publish -p waffles-solana-measure
cargo publish -p waffles-solana-memory-management
cargo publish -p waffles-solana-merkle-tree
cargo publish -p waffles-solana-metrics
cargo publish -p waffles-solana-net-utils
cargo publish -p waffles-solana-notifier
cargo publish -p waffles-solana-perf
cargo publish -p waffles-solana-poh
cargo publish -p waffles-solana-program-runtime
cargo publish -p waffles-solana-program-test
cargo publish -p waffles-solana-programs/bpf_loader
cargo publish -p waffles-solana-programs/compute-budget
cargo publish -p waffles-solana-programs/config
cargo publish -p waffles-solana-programs/stake
cargo publish -p waffles-solana-programs/vote
cargo publish -p waffles-solana-programs/zk-token-proof
cargo publish -p waffles-solana-pubsub-client
cargo publish -p waffles-solana-quic-client
cargo publish -p waffles-solana-rayon-threadlimit
cargo publish -p waffles-solana-remote-wallet
cargo publish -p waffles-solana-rpc
cargo publish -p waffles-solana-rpc-client
cargo publish -p waffles-solana-rpc-client-api
cargo publish -p waffles-solana-rpc-client-nonce-utils
cargo publish -p waffles-solana-runtime
cargo publish -p waffles-solana-sdk
cargo publish -p waffles-solana-sdk/macro
cargo publish -p waffles-solana-sdk/program
cargo publish -p waffles-solana-send-transaction-service
cargo publish -p waffles-solana-stake-accounts
cargo publish -p waffles-solana-storage-bigtable
cargo publish -p waffles-solana-storage-proto
cargo publish -p waffles-solana-streamer
cargo publish -p waffles-solana-sys-tuner
cargo publish -p waffles-solana-test-validator
cargo publish -p waffles-solana-thin-client
cargo publish -p waffles-solana-tokens
cargo publish -p waffles-solana-tpu-client
cargo publish -p waffles-solana-transaction-status
cargo publish -p waffles-solana-udp-client
cargo publish -p waffles-solana-validator
cargo publish -p waffles-solana-version
cargo publish -p waffles-solana-watchtower
cargo publish -p waffles-solana-zk-token-sdk