[package]
name = "waffles-solana-sbf-rust-sysvar"
version = "1.16.0-alpha.9"
description = "Waffle Labs maintained Solana SBF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
name = "solana-sbf-rust-sysvar"
version = "1.16.0-alpha.9"
description = "Solana SBF test program written in Rust"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-sbf-rust-sysvar"
edition = "2021"

[dependencies]
solana-program = { path = "../../../../sdk/program", version = "=1.16.0-alpha.9" }

[dev-dependencies]
solana-program-runtime = { path = "../../../../program-runtime", version = "=1.16.0-alpha.9" }
solana-program-test = { path = "../../../../program-test", version = "=1.16.0-alpha.9" }
solana-sdk = { path = "../../../../sdk", version = "=1.16.0-alpha.9" }
solana-program = { path = "../../../../sdk/program", version = "=1.16.0-alpha.9" }

[dev-dependencies]
solana-program-runtime = { path = "../../../../program-runtime", version = "=1.16.0-alpha.9" }
solana-program-test = { path = "../../../../program-test", version = "=1.16.0-alpha.9" }
solana-sdk = { path = "../../../../sdk", version = "=1.16.0-alpha.9" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
