[package]
name = "waffles-solana-sbf-rust-many-args-dep"
version = "1.16.0"
description = "Waffle Labs maintained Solana SBF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
name = "solana-sbf-rust-many-args-dep"
version = "1.16.0"
description = "Solana SBF test program written in Rust"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-sbf-rust-many-args-dep"
edition = "2021"

[dependencies]
solana-program = { path = "../../../../sdk/program", version = "=1.16.0" }
solana-program = { path = "../../../../sdk/program", version = "=1.16.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
