[package]
name = "waffles-solana-rpc"
version = "1.15.0-2"
description = "Waffle Labs maintained Solana RPC"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-rpc"
edition = "2021"

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
dashmap = "4.0.2"
itertools = "0.10.5"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0" }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
libc = "0.2.131"
log = "0.4.17"
rayon = "1.5.3"
regex = "1.6.0"
serde = "1.0.144"
serde_derive = "1.0.103"
serde_json = "1.0.83"
soketto = "0.7"
solana-account-decoder = { package = "waffles-solana-account-decoder", path = "../account-decoder", version = "=1.15.0-2" }
solana-client = { package = "waffles-solana-client", path = "../client", version = "=1.15.0-2" }
waffles-solana-entry = { path = "../entry", version = "=1.15.0-2" }
solana-faucet = { package = "waffles-solana-faucet", path = "../faucet", version = "=1.15.0-2" }
solana-gossip = { package = "waffles-solana-gossip", path = "../gossip", version = "=1.15.0-2" }
waffles-solana-ledger = { path = "../ledger", version = "=1.15.0-2" }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.15.0-2" }
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.15.0-2" }
solana-perf = { package = "waffles-solana-perf", path = "../perf", version = "=1.15.0-2" }
waffles-solana-poh = { path = "../poh", version = "=1.15.0-2" }
solana-rayon-threadlimit = { package = "waffles-solana-rayon-threadlimit", path = "../rayon-threadlimit", version = "=1.15.0-2" }
solana-rpc-client-api = { package = "waffles-solana-rpc-client-api", path = "../rpc-client-api", version = "=1.15.0-2" }
solana-runtime = { package = "waffles-solana-runtime", path = "../runtime", version = "=1.15.0-2" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0-2" }
solana-send-transaction-service = { package = "waffles-solana-send-transaction-service", path = "../send-transaction-service", version = "=1.15.0-2" }
solana-stake-program = { package = "waffles-solana-stake-program", path = "../programs/stake", version = "=1.15.0-2" }
waffles-solana-storage-bigtable = { path = "../storage-bigtable", version = "=1.15.0-2" }
solana-streamer = { package = "waffles-solana-streamer", path = "../streamer", version = "=1.15.0-2" }
waffles-solana-tpu-client = { path = "../tpu-client", version = "=1.15.0-2", default-features = false }
solana-transaction-status = { package = "waffles-solana-transaction-status", path = "../transaction-status", version = "=1.15.0-2" }
solana-version = { package = "waffles-solana-version", path = "../version", version = "=1.15.0-2" }
solana-vote-program = { package = "waffles-solana-vote-program", path = "../programs/vote", version = "=1.15.0-2" }
spl-token = { version = "=3.5.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "=0.5.0", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec", "compat"] }

[dev-dependencies]
serial_test = "0.9.0"
solana-address-lookup-table-program = { package = "waffles-solana-address-lookup-table-program", path = "../programs/address-lookup-table", version = "=1.15.0-2" }
solana-net-utils = { package = "waffles-solana-net-utils", path = "../net-utils", version = "=1.15.0-2" }
solana-stake-program = { package = "waffles-solana-stake-program", path = "../programs/stake", version = "=1.15.0-2" }
symlink = "0.1.0"

[lib]
crate-type = ["lib"]
name = "solana_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
