[package]
name = "waffles-solana-cargo-build-sbf"
version = "1.16.0-alpha.3"
description = "Waffle Labs maintained Compile a local package and all of its dependencies using the Solana SBF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
homepage = "https://waffles.so/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bzip2 = "0.4.4"
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo", "env"] }
log = { version = "0.4.17", features = ["std"] }
regex = "1.6.0"
solana-download-utils = { package = "waffles-solana-download-utils",path = "../../download-utils", version = "=1.16.0-alpha.2" }
solana-logger = { package = "waffles-solana-logger", path = "../../logger", version = "=1.16.0-alpha.2" }
solana-sdk = { package = "waffles-solana-sdk", path = "..", version = "=1.16.0-alpha.2" }
reqwest = { version = "0.11", features = ["blocking"] }
semver = "1.0"
tar = "0.4.38"

[dev-dependencies]
assert_cmd = "*"
predicates = "2.1"
serial_test = "*"

[features]
program = []

[[bin]]
name = "cargo-build-sbf"
path = "src/main.rs"
