[package]
name = "waffles-solana-transaction-dos"
version = "1.16.0"
repository = "https://github.com/waffles-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://waffles.so/"
publish = false

[dependencies]
bincode = "1.3.3"
clap = "2.33.1"
log = "0.4.17"
rand = "0.7.0"
rayon = "1.5.3"

[dev-dependencies]
solana-local-cluster = { package = "waffles-solana-local-cluster", path = "../local-cluster", version = "=1.16.0" }
solana-clap-utils = { package = "waffles-solana-clap-utils", path = "../clap-utils", version = "=1.16.0" }
solana-cli = { package = "waffles-solana-cli", path = "../cli", version = "=1.16.0" }
solana-client = { package = "waffles-solana-client", path = "../client", version = "=1.16.0" }
solana-core = { package = "waffles-solana-core", path = "../core", version = "=1.16.0" }
solana-faucet = { package = "waffles-solana-faucet", path = "../faucet", version = "=1.16.0" }
solana-gossip = { package = "waffles-solana-gossip", path = "../gossip", version = "=1.16.0" }
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.16.0" }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.16.0" }
solana-net-utils = { package = "waffles-solana-net-utils", path = "../net-utils", version = "=1.16.0" }
solana-rpc-client = { package = "waffles-solana-rpc-client", path = "../rpc-client", version = "=1.16.0", default-features = false }
solana-runtime = { package = "waffles-solana-runtime", path = "../runtime", version = "=1.16.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.16.0" }
solana-streamer = { package = "waffles-solana-streamer", path = "../streamer", version = "=1.16.0" }
solana-transaction-status = { package = "waffles-solana-transaction-status", path = "../transaction-status", version = "=1.16.0" }
solana-version = { package = "waffles-solana-version", path = "../version", version = "=1.16.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
