[package]
name = "waffles-solana-thin-client"
version = "1.16.0-alpha.4"
description = "Waffle Labs maintained Solana Thin Client"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-thin-client"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.17"
rayon = "1.5.3"
solana-connection-cache = { package = "waffles-solana-connection-cache", path = "../connection-cache", version = "=1.16.0-alpha.4", default-features = false }
solana-rpc-client = { package = "waffles-solana-rpc-client", path = "../rpc-client", version = "=1.16.0-alpha.4", default-features = false }
solana-rpc-client-api = { package = "waffles-solana-rpc-client-api", path = "../rpc-client-api", version = "=1.16.0-alpha.4" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.16.0-alpha.4" }
solana-tpu-client = { package = "waffles-solana-tpu-client", path = "../tpu-client", version = "=1.16.0-alpha.4", default-features = false }

[dev-dependencies]
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.16.0-alpha.4" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
