[package]
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
edition = "2021"
name = "waffles-solana-validator"
description = "Waffle Labs maintained Blockchain, Rebuilt for Scale"
version = "1.15.0"
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-validator"
default-run = "waffles-solana-validator"

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
fd-lock = "3.0.6"
indicatif = "0.17.1"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils = "18.0.0"
lazy_static = "1.4.0"
log = "0.4.17"
num_cpus = "1.13.1"
rand = "0.7.0"
rayon = "1.5.3"
serde = "1.0.144"
serde_json = "1.0.83"
serde_yaml = "0.9.13"
waffles-solana-clap-utils = { path = "../clap-utils", version = "=1.15.0" }
waffles-solana-cli-config = { path = "../cli-config", version = "=1.15.0" }
waffles-solana-core = { path = "../core", version = "=1.15.0" }
waffles-solana-download-utils = { path = "../download-utils", version = "=1.15.0" }
waffles-solana-entry = { path = "../entry", version = "=1.15.0" }
waffles-solana-faucet = { path = "../faucet", version = "=1.15.0" }
waffles-solana-genesis-utils = { path = "../genesis-utils", version = "=1.15.0" }
waffles-solana-gossip = { path = "../gossip", version = "=1.15.0" }
waffles-solana-ledger = { path = "../ledger", version = "=1.15.0" }
waffles-solana-logger = { path = "../logger", version = "=1.15.0" }
waffles-solana-metrics = { path = "../metrics", version = "=1.15.0" }
waffles-solana-net-utils = { path = "../net-utils", version = "=1.15.0" }
waffles-solana-perf = { path = "../perf", version = "=1.15.0" }
waffles-solana-poh = { path = "../poh", version = "=1.15.0" }
waffles-solana-rpc = { path = "../rpc", version = "=1.15.0" }
waffles-solana-rpc-client = { path = "../rpc-client", version = "=1.15.0", default-features = false }
waffles-solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.0" }
solana-runtime = { package = "waffles-solana-runtime", path = "../runtime", version = "=1.15.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0" }
solana-send-transaction-service = { package = "waffles-solana-send-transaction-service", path = "../send-transaction-service", version = "=1.15.0" }
waffles-solana-storage-bigtable = { path = "../storage-bigtable", version = "=1.15.0" }
waffles-solana-streamer = { path = "../streamer", version = "=1.15.0" }
waffles-solana-test-validator = { path = "../test-validator", version = "=1.15.0" }
waffles-solana-tpu-client = { path = "../tpu-client", version = "=1.15.0", default-features = false }
waffles-solana-version = { path = "../version", version = "=1.15.0" }
waffles-solana-vote-program = { path = "../programs/vote", version = "=1.15.0" }
symlink = "0.1.0"

[dev-dependencies]
waffles-solana-account-decoder = { path = "../account-decoder", version = "=1.15.0" }
spl-token-2022 = { version = "=0.5.0", features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"] }

[target."cfg(unix)".dependencies]
libc = "0.2.131"
signal-hook = "0.3.14"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
