[package]
name = "waffles-solana-runtime"
version = "1.16.0-alpha.5"
description = "Waffle Labs maintained Solana runtime"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-runtime"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.3"
blake3 = "1.3.1"
bv = { version = "0.11.1", features = ["serde"] }
bytemuck = "1.11.0"
byteorder = "1.4.3"
bzip2 = "0.4.4"
crossbeam-channel = "0.5"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
dir-diff = "0.3.2"
flate2 = "1.0.24"
fnv = "1.0.7"
im = { version = "15.1.0", features = ["rayon", "serde"] }
index_list = "0.2.7"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
lru = "0.7.7"
lz4 = "1.24.0"
memmap2 = "0.5.8"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
num_cpus = "1.13.1"
once_cell = "1.13.0"
ouroboros = "0.15.0"
rand = "0.7.0"
rayon = "1.5.3"
regex = "1.6.0"
serde = { version = "1.0.152", features = ["rc"] }
serde_derive = "1.0.103"
solana-address-lookup-table-program = { package = "waffles-solana-address-lookup-table-program", path = "../programs/address-lookup-table", version = "=1.16.0-alpha.5" }
solana-bpf-loader-program = { package = "waffles-solana-bpf-loader-program", path = "../programs/bpf_loader", version = "=1.16.0-alpha.5" }
solana-bucket-map = { package = "waffles-solana-bucket-map", path = "../bucket_map", version = "=1.16.0-alpha.5" }
solana-compute-budget-program = { package = "waffles-solana-compute-budget-program", path = "../programs/compute-budget", version = "=1.16.0-alpha.5" }
solana-config-program = { package = "waffles-solana-config-program", path = "../programs/config", version = "=1.16.0-alpha.5" }
solana-frozen-abi = { package = "waffles-solana-frozen-abi", path = "../frozen-abi", version = "=1.16.0-alpha.5" }
solana-frozen-abi-macro = { package = "waffles-solana-frozen-abi-macro", path = "../frozen-abi/macro", version = "=1.16.0-alpha.5" }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.16.0-alpha.5" }
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.16.0-alpha.5" }
solana-perf = { package = "waffles-solana-perf", path = "../perf", version = "=1.16.0-alpha.5" }
solana-program-runtime = { package = "waffles-solana-program-runtime", path = "../program-runtime", version = "=1.16.0-alpha.5" }
solana-rayon-threadlimit = { package = "waffles-solana-rayon-threadlimit", path = "../rayon-threadlimit", version = "=1.16.0-alpha.5" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.16.0-alpha.5" }
solana-stake-program = { package = "waffles-solana-stake-program", path = "../programs/stake", version = "=1.16.0-alpha.5" }
solana-vote-program = { package = "waffles-solana-vote-program", path = "../programs/vote", version = "=1.16.0-alpha.5" }
solana-zk-token-proof-program = { package = "waffles-solana-zk-token-proof-program", path = "../programs/zk-token-proof", version = "=1.16.0-alpha.5" }
solana-zk-token-sdk = { package = "waffles-solana-zk-token-sdk", path = "../zk-token-sdk", version = "=1.16.0-alpha.5" }
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
symlink = "0.1.0"
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0"
zstd = "0.11.2"

[lib]
crate-type = ["lib"]
name = "solana_runtime"

[dev-dependencies]
assert_matches = "1.5.0"
ed25519-dalek = "=1.0.1"
libsecp256k1 = "0.6.0"
memoffset = "0.8"
rand_chacha = "0.2.2"
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.16.0-alpha.5" }
static_assertions = "1.1.0"
test-case = "2.2.2"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"

[[bench]]
name = "prioritization_fee_cache"
