[package]
name = "waffles-solana-compute-budget-program"
description = "Waffle Labs maintained Solana Compute Budget program"
version = "1.16.0-alpha.4"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-compute-budget-program"
repository = "https://github.com/waffles-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
solana-program-runtime = { package = "waffles-solana-program-runtime", path = "../../program-runtime", version = "=1.16.0-alpha.4" }
solana-sdk = { package = "waffles-solana-sdk", path = "../../sdk", version = "=1.16.0-alpha.4" }

[lib]
crate-type = ["lib"]
name = "solana_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
