# This package only exists to avoid circular dependencies during cargo publish:
# solana-bpf-loader-program -> solana-program-test -> solana-bpf-loader-program

[package]
name = "waffles-solana-bpf-loader-program-tests"
version = "1.16.0-alpha.2"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
solana-bpf-loader-program = { package = "waffles-solana-bpf-loader-program", path = "../bpf_loader", version = "=1.16.0-alpha.2" }
solana-program-test = { package = "waffles-solana-program-test", path = "../../program-test", version = "=1.16.0-alpha.2" }
solana-sdk = { package = "waffles-solana-sdk", path = "../../sdk", version = "=1.16.0-alpha.2" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
