[package]
name = "waffles-solana-program-runtime"
version = "1.15.0-2"
description = "Waffle Labs maintained Solana program runtime"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-program-runtime"
edition = "2021"

[dependencies]
base64 = "0.13"
bincode = "1.3.3"
eager = "0.1.0"
enum-iterator = "1.2.0"
itertools =  "0.10.1"
libc = "0.2.101"
libloading = "0.7.0"
log = "0.4.14"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
rand = "0.7.0"
serde = { version = "1.0.129", features = ["derive", "rc"] }
solana-frozen-abi = { package = "waffles-solana-frozen-abi", path = "../frozen-abi", version = "=1.15.0-2" }
solana-frozen-abi-macro = { package = "waffles-solana-frozen-abi-macro", path = "../frozen-abi/macro", version = "=1.15.0-2" }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.15.0-2" }
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.15.0-2" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0-2" }
solana_rbpf = "=0.2.38"
thiserror = "1.0"

[dev-dependencies]
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.15.0-2" }

[lib]
crate-type = ["lib"]
name = "solana_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
