[package]
name = "waffles-solana-udp-client"
version = "1.15.0"
description = "Waffle Labs maintained Solana UDP Client"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-udp-client"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
solana-net-utils = { path = "../net-utils", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-streamer = { path = "../streamer", version = "=1.15.0" }
solana-tpu-client = { path = "../tpu-client", version = "=1.15.0" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
