[package]
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
edition = "2021"
name = "waffles-solana-watchtower"
description = "Waffle Labs maintained Blockchain, Rebuilt for Scale"
version = "1.15.0-1"
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-watchtower"

[dependencies]
clap = "2.33.1"
humantime = "2.0.1"
log = "0.4.17"
solana-clap-utils = { package = "waffles-solana-clap-utils", path = "../clap-utils", version = "=1.15.0" }
waffles-solana-cli-config = { path = "../cli-config", version = "=1.15.0" }
waffles-solana-cli-output = { path = "../cli-output", version = "=1.15.0" }
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.15.0" }
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.15.0" }
waffles-solana-notifier = { path = "../notifier", version = "=1.15.0" }
solana-rpc-client = { package = "waffles-solana-rpc-client", path = "../rpc-client", version = "=1.15.0", default-features = false }
solana-rpc-client-api = { package = "waffles-solana-rpc-client-api", path = "../rpc-client-api", version = "=1.15.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0" }
solana-version = { package = "waffles-solana-version", path = "../version", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
