[package]
name = "waffles-solana-quic-client"
version = "1.15.0"
description = "Waffle Labs maintained Solana Quic Client"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-quic-client"
edition = "2021"

[dependencies]
async-mutex = "1.4.0"
async-trait = "0.1.57"
futures = "0.3"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
quinn = "0.8.4"
quinn-proto = "0.8.4"
quinn-udp = "0.1.3"
rustls = { version = "0.20.6", features = ["dangerous_configuration"] }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.15.0" }
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.15.0" }
solana-net-utils = { package = "waffles-solana-net-utils", path = "../net-utils", version = "=1.15.0" }
solana-rpc-client-api = { package = "waffles-solana-rpc-client-api", path = "../rpc-client-api", version = "=1.15.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0" }
solana-streamer = { package = "waffles-solana-streamer", path = "../streamer", version = "=1.15.0" }
waffles-solana-tpu-client = { path = "../tpu-client", version = "=1.15.0" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
crossbeam-channel = "0.5"
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.15.0" }
waffles-solana-perf = { path = "../perf", version = "=1.15.0" }
