[package]
name = "waffles-solana-poh-bench"
version = "1.16.0-alpha.6"
repository = "https://github.com/waffles-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-poh-bench"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = "0.4.17"
rand = "0.7.0"
rayon = "1.5.3"
solana-entry = { package = "waffles-solana-entry", path = "../entry", version = "=1.16.0-alpha.6" }
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.16.0-alpha.6" }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.16.0-alpha.6" }
solana-perf = { package = "waffles-solana-perf", path = "../perf", version = "=1.16.0-alpha.6" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.16.0-alpha.6" }
solana-version = { package = "waffles-solana-version", path = "../version", version = "=1.16.0-alpha.6" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
