[package]
name = "waffles-rbpf-cli"
version = "1.15.0"
description = "Waffle Labs maintained CLI to test and analyze SBF programs"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/solana-labs/rbpf"
homepage = "https://waffles.so/"
keywords = ["SBF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
serde = "1.0.144"
serde_json = "1.0.83"
waffles-solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.15.0" }
waffles-solana-logger = { path = "../logger", version = "=1.15.0" }
waffles-solana-program-runtime = { path = "../program-runtime", version = "=1.15.0" }
waffles-solana-sdk = { path = "../sdk", version = "=1.15.0" }
waffles-solana_rbpf = { version = "=0.2.38", features = ["debugger"] }
