[package]
name = "waffles-solana-cargo-test-bpf"
version = "1.15.0.1"
description = "Waffle Labs maintained Execute all unit and integration tests after building with the Solana SBF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
homepage = "https://waffles.so/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo"] }

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
