[package]
name = "waffles-solana-frozen-abi-macro"
version = "1.15.0-1"
description = "Waffle Labs maintained Solana Frozen ABI Macro"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-frozen-abi-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits", "visit-mut"] }

[build-dependencies]
rustc_version = "0.4"
