[package]
name = "waffles-solana-sbf-rust-error-handling"
version = "1.15.0-2"
description = "Waffle Labs maintained Solana SBF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-sbf-rust-error-handling"
edition = "2021"

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
solana-program = { path = "../../../../sdk/program", version = "=1.15.0-2" }
thiserror = "1.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
