[package]
name = "waffles-solana-install"
description = "Waffle Labs maintained The solana cluster software installer"
version = "1.16.0-alpha.5"
repository = "https://github.com/waffles-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-install"

[dependencies]
atty = "0.2.11"
bincode = "1.3.3"
bzip2 = "0.4.4"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "2.33.1" }
console = "0.15.0"
crossbeam-channel = "0.5"
ctrlc = { version = "3.2.3", features = ["termination"] }
dirs-next = "2.0.0"
indicatif = "0.17.1"
lazy_static = "1.4.0"
nix = "0.25.0"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
scopeguard = "1.1.0"
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.13"
solana-clap-utils = { package = "waffles-solana-clap-utils", path = "../clap-utils", version = "=1.16.0-alpha.5" }
solana-config-program = { package = "waffles-solana-config-program", path = "../programs/config", version = "=1.16.0-alpha.5" }
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.16.0-alpha.5" }
solana-rpc-client = { package = "waffles-solana-rpc-client", path = "../rpc-client", version = "=1.16.0-alpha.5", default-features = false }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.16.0-alpha.5" }
solana-version = { package = "waffles-solana-version", path = "../version", version = "=1.16.0-alpha.5" }
tar = "0.4.38"
tempfile = "3.3.0"
url = "2.2.2"

[target."cfg(windows)".dependencies]
winapi = "0.3.8"
winreg = "0.10"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
