[package]
name = "waffles-solana-rpc-test"
version = "1.16.0-alpha.6"
description = "Waffle Labs maintained Solana RPC Test"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-rpc-test"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
futures-util = "0.3.26"
log = "0.4.17"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde = "1.0.152"
serde_json = "1.0.83"

[dev-dependencies]
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.16.0-alpha.6" }
solana-account-decoder = { package = "waffles-solana-account-decoder", path = "../account-decoder", version = "=1.16.0-alpha.6" }
solana-client = { package = "waffles-solana-client", path = "../client", version = "=1.16.0-alpha.6" }
solana-pubsub-client = { package = "waffles-solana-pubsub-client", path = "../pubsub-client", version = "=1.16.0-alpha.6" }
solana-rpc = { package = "waffles-solana-rpc", path = "../rpc", version = "=1.16.0-alpha.6" }
solana-rpc-client = { package = "waffles-solana-rpc-client", path = "../rpc-client", version = "=1.16.0-alpha.6", default-features = false }
solana-rpc-client-api = { package = "waffles-solana-rpc-client-api", path = "../rpc-client-api", version = "=1.16.0-alpha.6" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.16.0-alpha.6" }
solana-streamer = { package = "waffles-solana-streamer", path = "../streamer", version = "=1.16.0-alpha.6" }
solana-test-validator = { package = "waffles-solana-test-validator", path = "../test-validator", version = "=1.16.0-alpha.6" }
solana-tpu-client = { package = "waffles-solana-tpu-client", path = "../tpu-client", version = "=1.16.0-alpha.6", default-features = false }
solana-transaction-status = { package = "waffles-solana-transaction-status", path = "../transaction-status", version = "=1.16.0-alpha.6" }
tokio = { version = "~1.14.1", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
