[package]
name = "waffles-solana-rpc-test"
version = "1.15.0"
description = "Waffle Labs maintained Solana RPC Test"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-rpc-test"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
futures-util = "0.3.25"
log = "0.4.17"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde = "1.0.144"
serde_json = "1.0.83"
waffles-solana-account-decoder = { path = "../account-decoder", version = "=1.15.0" }
waffles-solana-client = { package = "waffles-solana-client", path = "../client", version = "=1.15.0" }
waffles-solana-pubsub-client = { path = "../pubsub-client", version = "=1.15.0" }
waffles-solana-rpc = { path = "../rpc", version = "=1.15.0" }
waffles-solana-rpc-client = { path = "../rpc-client", version = "=1.15.0", default-features = false }
waffles-solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0" }
waffles-solana-streamer = { path = "../streamer", version = "=1.15.0" }
waffles-solana-test-validator = { path = "../test-validator", version = "=1.15.0" }
waffles-solana-tpu-client = { path = "../tpu-client", version = "=1.15.0", default-features = false }
waffles-solana-transaction-status = { path = "../transaction-status", version = "=1.15.0" }
tokio = { version = "~1.14.1", features = ["full"] }

[dev-dependencies]
waffles-solana-logger = { path = "../logger", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
