[package]
name = "waffles-solana-upload-perf"
version = "1.15.0"
description = "Waffle Labs maintained Metrics Upload Utility"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
edition = "2021"
homepage = "https://waffles.so/"
publish = false

[dependencies]
serde_json = "1.0.83"
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.15.0" }

[[bin]]
name = "solana-upload-perf"
path = "src/upload-perf.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
