[package]
name = "waffles-solana-sbf-rust-sha"
version = "1.15.0-1"
description = "Waffle Labs maintained Solana SBF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-sbf-rust-sha"
edition = "2021"

[dependencies]
blake3 = "1.0.0"
solana-program = { path = "../../../../sdk/program", version = "=1.15.0" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
