[package]
name = "waffles-solana-rpc-client"
version = "1.15.0"
description = "Waffle Labs maintained Solana RPC Client"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-rpc-client"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
indicatif = { version = "0.17.1", optional = true }
log = "0.4.17"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
semver = "1.0.14"
serde = "1.0.144"
serde_derive = "1.0.103"
serde_json = "1.0.83"
solana-account-decoder = { package = "waffles-solana-account-decoder", path = "../account-decoder", version = "=1.15.0" }
solana-rpc-client-api = { package = "waffles-solana-rpc-client-api", path = "../rpc-client-api", version = "=1.15.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0" }
solana-transaction-status = { package = "waffles-solana-transaction-status", path = "../transaction-status", version = "=1.15.0" }
solana-version = { package = "waffles-solana-version", path = "../version", version = "=1.15.0" }
waffles-solana-vote-program = { path = "../programs/vote", version = "=1.15.0" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
assert_matches = "1.5.0"
crossbeam-channel = "0.5"
futures = "0.3"
jsonrpc-core = "18.0.0"
jsonrpc-http-server = "18.0.0"

[features]
default = ["spinner"]
# Support rpc-client methods that feature a spinner progress bar for
# command-line interfaces
spinner = ["dep:indicatif"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
