[package]
name = "waffles-solana-send-transaction-service"
version = "1.15.0"
description = "Waffle Labs maintained Solana send transaction service"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4.17"
solana-client = { package = "waffles-solana-client", path = "../client", version = "=1.15.0" }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.15.0" }
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.15.0" }
solana-runtime = { package = "waffles-solana-runtime", path = "../runtime", version = "=1.15.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0" }
waffles-solana-tpu-client = { path = "../tpu-client", version = "=1.15.0", default-features = false }

[dev-dependencies]
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
