[package]
name = "waffles-solana-store-tool"
description = "Waffle Labs maintained Tool to inspect append vecs"
version = "1.16.0-alpha.4"
repository = "https://github.com/waffles-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://waffles.so/"
publish = false

[dependencies]
clap = "2.33.1"
log = { version = "0.4.17" }
solana-logger = { package = "waffles-solana-logger", path = "../../logger", version = "=1.16.0-alpha.4" }
solana-runtime = { package = "waffles-solana-runtime", path = "..", version = "=1.16.0-alpha.4" }
solana-sdk = { package = "waffles-solana-sdk", path = "../../sdk", version = "=1.16.0-alpha.4" }
solana-version = { package = "waffles-solana-version", path = "../../version", version = "=1.16.0-alpha.4" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
