[package]
name = "waffles-solana-poh"
version = "1.15.0-2"
description = "Waffle Labs maintained Solana PoH"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-poh"
edition = "2021"

[dependencies]
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
log = "0.4.17"
waffles-solana-entry = { path = "../entry", version = "=1.15.0-2" }
waffles-solana-ledger = { path = "../ledger", version = "=1.15.0-2" }
solana-measure = { package = "waffles-solana-measure", path = "../measure", version = "=1.15.0-2" }
solana-metrics = { package = "waffles-solana-metrics", path = "../metrics", version = "=1.15.0-2" }
solana-runtime = { package = "waffles-solana-runtime", path = "../runtime", version = "=1.15.0-2" }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0-2" }
waffles-solana-sys-tuner = { path = "../sys-tuner", version = "=1.15.0-2" }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
matches = "0.1.9"
rand = "0.7.0"
solana-logger = { package = "waffles-solana-logger", path = "../logger", version = "=1.15.0-2" }
solana-perf = { package = "waffles-solana-perf", path = "../perf", version = "=1.15.0-2" }

[lib]
crate-type = ["lib"]
name = "solana_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
