[package]
name = "waffles-solana-vote-program"
version = "1.15.0.1"
description = "Waffle Labs maintained Solana Vote program"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-vote-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.17"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.144"
serde_derive = "1.0.103"
solana-frozen-abi = { package = "waffles-solana-frozen-abi", path = "../../frozen-abi", version = "=1.15.0" }
solana-frozen-abi-macro = { package = "waffles-solana-frozen-abi-macro", path = "../../frozen-abi/macro", version = "=1.15.0" }
solana-metrics = { package = "waffles-solana-metrics", path = "../../metrics", version = "=1.15.0" }
solana-program = { package = "waffles-solana-program", path = "../../sdk/program", version = "=1.15.0" }
solana-program-runtime = { package = "waffles-solana-program-runtime", path = "../../program-runtime", version = "=1.15.0" }
solana-sdk = { package = "waffles-solana-sdk", path = "../../sdk", version = "=1.15.0" }
thiserror = "1.0"

[dev-dependencies]
solana-logger = { package = "waffles-solana-logger", path = "../../logger", version = "=1.15.0" }
test-case = "2.2.2"

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
