[package]
name = "waffles-solana-metrics"
version = "1.15.0-1"
description = "Waffle Labs maintained Solana Metrics"
authors = ["Solana Maintainers <maintainers@solana.foundation", "Waffle Labs Maintainers <maintainers@waffles.so>"]
repository = "https://github.com/waffles-labs/solana"
license = "Apache-2.0"
homepage = "https://waffles.so/"
documentation = "https://docs.rs/waffles-solana-metrics"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
gethostname = "0.2.3"
lazy_static = "1.4.0"
log = "0.4.17"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
solana-sdk = { package = "waffles-solana-sdk", path = "../sdk", version = "=1.15.0" }

[dev-dependencies]
env_logger = "0.9.3"
rand = "0.7.0"
serial_test = "0.9.0"

[lib]
name = "solana_metrics"

[[bench]]
name = "metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
